export const ENV = {
  API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:3000',
  ACCESS_LEEWAY_SECONDS: Number(process.env.NEXT_PUBLIC_ACCESS_LEEWAY_SECONDS ?? 15),
  PROACTIVE_REFRESH_WINDOW_SECONDS: Number(process.env.NEXT_PUBLIC_PROACTIVE_REFRESH_WINDOW_SECONDS ?? 60),
};


